---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhQcXJzbFdnXzZSWjlZOE0tQXdvbG4xTU5RbzNBUWM0UmwwUGpERXk2ODQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJhOTQzMTgwMC0yYjc1LTQyOTUtOTFkMS00YjZhZjc2ZWU3NGIiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.Y93h_zas1noYO2yYxbVwvZ__ONRZWGmF7GlG9GgBZ5_1h6_f393VuQi3oSG0QnQfJYlf3yyzI9Pm4Qo5EyU_tF18_S-goZ5lhJrisVBnh-OBb2AQy9eGlHoBUAAIxIKKK2aHTvVhLDIgrlO2LYY_vMvr6z5YLCq-lnEFNf6_d4l9fePw3q9Be6WtH4vl5G4c9mQDtLVoGUpT32eleRGetANcdLXDhgafrspYLR1SV9Tct0VlOaNXGPVprkMIYQHgDvgAsaKtFOpuxiQiMFiA6xU0z7pPffI0uasqAyVEKzofVoCV533OuX3xFXgq-kP5komqXqo6oleWpYu-wug-10c4gqiCQVfbr3mogVOJp_kksTEexJBZJI--D9Zvi71Ncex5mjUqR3DUm8vAs49UCgAhl16wD3_WE3OCOl8WDliuwUADBxCNWxHBz0wPkeobpzfIJAeBILb1NKXF4_Ekk8pGTgiBvjbwhJ3SbPnhQ9KZll3pMejgGOfwYp-KYPGu8JiGadOXdJvuvxai4SZYMtQMnmXSa5gL-UIcd9BcNP4_1m39E11NUSd-b1UWF6a9ut1Gp0bgabzE_-cpq3oKqYh3YtX0ON9rVE9A-NcT8hLH9nnKl21eLXdzHthKyMaDOXGXfznOkyW2CXfr0o4kfVDk--c2_1tnO0FLOBfc_AM
  GITHUB_TOKEN: <place here gh token>
